<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>
    <RootNamespace>rc2_dvm</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>RC2-DVM</Title>
    <Description>RadioConsole2 DVM FNE Interface Daemon</Description>
    <Copyright>Copyright (c) 2025 Patrick McDonnell W3AXL</Copyright>
    <Product>RadioConsole2 DVM FNE Interface Daemon</Product>
    <Platforms>AnyCPU</Platforms>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<DefineConstants>$(ExtraConstants)</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>TRACE;$(ExtraConstants)</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(ExtraConstants)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitInfo" Version="3.5.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.WinMM" Version="2.2.1" Condition="'$(RuntimeIdentifier)' == 'win-x86' OR '$(RuntimeIdentifier)' == 'win-x64' OR '$(RuntimeIdentifier)' == 'win-arm64'" />
    <PackageReference Include="NWaves" Version="0.9.6" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="SIPSorcery" Version="8.0.7" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fnecore\fnecore.csproj" />
    <ProjectReference Include="..\rc2-core\rc2-core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.example.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config.yml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
